tap "homebrew/bundle"

# Install core CLI tools
brew "tmux"
brew "bash-completion"
brew "coreutils"
brew "diff-so-fancy"
brew "fzf"
brew "gh"
brew "gnupg"
brew "htop"
brew "jq"
brew "ripgrep"
brew "watch"
brew "ykman"
brew "yq"

# Install tech-specific tooling
brew "temporal"
brew "hadolint"
brew "go"
brew "kubectx"
brew "kubernetes-cli"
brew "kubie"
brew "helm"
brew "awscli"

cask "orbstack"
cask "visual-studio-code"
cask "gather"
