#!/bin/bash

############################################################################################
# This script creates symlinks from the home directory to any desired dotfiles in ~/dotfiles
############################################################################################

# Create a variable that ensures we can run a script in the same directory no matter how this script is called
__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

DOTFILES_DIR="~/.dotfiles"

# list of files/folders to symlink in homedir
FILES_TO_SYMLINK=".zshrc .zprofile .tmux.conf .Brewfile .gitconfig .tmux-powerlinerc .zsh"

# move any existing dotfiles in homedir to dotfiles_old directory, then create symlinks from the homedir to any files in the ~/dotfiles directory specified in $files
for file in $FILES_TO_SYMLINK; do
    FILE_LOCATION="${__dir}/$file"
    SYMLINK_LOCATION="$HOME/$file"
    echo "Creating symlink to $FILE_LOCATION in $SYMLINK_LOCATION."
    ln -s $FILE_LOCATION $SYMLINK_LOCATION
done
