#!/bin/bash

# Check if zsh is installed
if ! hash zsh 2>/dev/null; then
    echo "zsh isn't installed. Installing now..."
    sudo apt install -y zsh
    echo "Completed installing zsh."
else
    echo "zsh already installed."
fi

# Check if oh-my-zsh is installed
OMZDIR="$HOME/.oh-my-zsh"
if [ ! -d "$OMZDIR" ]; then
    echo 'Installing oh-my-zsh...'
    /bin/sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" --unattended
    echo 'Completed installing oh-my-zsh.'
else
    echo "oh-my-zsh already installed."
fi
