#!/bin/bash

# Check if oh-my-zsh is installed
OMZDIR="$HOME/.oh-my-zsh"
if [ ! -d "$OMZDIR" ]; then
    echo 'Installing oh-my-zsh...'
    /bin/sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    echo 'Completed installing oh-my-zsh.'
else
    echo 'Updating oh-my-zsh'
    upgrade_oh_my_zsh
fi

if ! hash zsh 2>/dev/null; then
    echo "zsh isn't installed. Installing now..."
    sudo apt install -y zsh
    echo "Completed installing zsh."
else
    echo "zsh already installed."
fi

# Change currenly running shell
if [ -z "$ZSH_NAME"]; then
    echo 'Changing default shell to zsh'
    chsh -s /bin/zsh
else
    echo 'Already using zsh'
fi
