#!/bin/bash

REPO_NAME=:".dotfiles"

# If .dotfiles folder doesn't already exist in $HOME, git clone it
# This is included so that this script can be run from a fresh installation
if [ ! -d "$HOME/$REPO_NAME" ] 
then
    (cd $HOME && git clone https://github.com/ProfMoo/$REPO_NAME)
fi

source (cd $HOME && ./$REPO_NAME/make_symlinks)
source (cd $HOME && ./$REPO_NAME/install_tools)
