#!/bin/bash

# Create a variable that ensures we can run a script in the same directory no matter how this script is called
__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# If .dotfiles folder doesn't already exist in $HOME, git clone it
# This is included so that this script can be run from a fresh installation
if [ ! -d "$HOME/.dotfiles" ] 
then
    (cd $HOME && git clone https://github.com/ProfMoo/.dotfiles)
fi

source ${__dir}/make_symlinks
source ${__dir}/install_tools
