#!/bin/bash

code --install-extension shan.code-settings-sync

echo "hello world"

defaults write -g InitialKeyRepeat -int 10 # normal minimum is 15 (225 ms)
defaults write -g KeyRepeat -int 1 # normal minimum is 2 (30 ms)
