#!/bin/zsh

echo "Downloading and installing tmux plugin manager (tpm)..."

[[ ! -d "$HOME/.tmux/plugins/tpm" ]] && git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

echo "Completed downloading and installing tmux plugin manager (tpm)."

exit 0
