#!/bin/bash

# Ensure tmux is installed
if ! hash tmux 2>/dev/null; then
    echo "tmux isn't installed. Installing now..."
    brew install tmux
    echo "Completed installing tmux."
else
    echo "tmux already installed."
fi
