#!/bin/zsh

echo "Downloading and installing tmux plugins..."

[[ ! -d "$HOME/.tmux/plugins/tpm" ]] && git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

[[ ! -d "$HOME/.tmux/plugins/tmux-powerline" ]] && git clone https://github.com/erikw/tmux-powerline.git ~/.tmux/plugins/tmux-powerline
[[ ! -d "$HOME/.tmux/plugins/tmux-powerline-fonts" ]] && git clone https://github.com/powerline/fonts.git --depth=1 ~/.tmux/plugins/tmux-powerline-fonts &&
    source ~/.tmux/plugins/tmux-powerline-fonts/install.sh

echo "Completed downloading and installing tmux plugins."

exit 0
